### PR TITLE
fix(compiler): Fix identifier comparison to be case insensitive

### LINKED ISSUE #2745: sqlc.embed() fails to recognize table aliases that aren't all lowercase
### Version

1.21.0

### What happened?

For the following query

```sql
-- name: FindAccountById :one
SELECT sqlc.embed(a), sqlc.embed(locMain), sqlc.embed(locAlt)
FROM Account a
LEFT JOIN Locations locMain ON a.MainAddressId = locMain.Id
LEFT JOIN Locations locAlt ON a.AlternateAddressId = locAlt.Id
WHERE a.Id = ? LIMIT 1;
```

sqlc generates the error below.

### Relevant log output

```shell
# package db
query.sql:23:1: unable to resolve table with "sqlc.embed(locmain)": relation "locmain" does not exist
```

### Database schema

_No response_

### SQL queries

_No response_

### Configuration

_No response_

### Playground URL

https://play.sqlc.dev/p/57a853fc5c03ece6498a05a4996a75d0f8e28a0a43e91bfcce27bc4ead25732b

### What operating system are you using?

_No response_

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

### PR DESCRIPTION
**Pull request by orisano**
close #2745

### CODE REVIEW

**Comment by kyleconroy** [comment]
@orisano Sorry about the test failures. Can you rebase from main? It should fix those failures.

**Comment by kyleconroy** [comment]
How will with work with quoted identifiers? Identifiers are case-insensitive unless they aren't.

**Comment by orisano** [comment]
I thought that quoted identifiers are handled by the parser for each engine and the compiler doesn't need to be aware of them.

**Comment by orisano** [comment]
```sql
CREATE TABLE t(`C` TEXT); 
SELECT c FROM t;
```
Is the expectation that this should not work?

**Comment by kyleconroy** [comment]
It depends on the database engine. That query does not work for PostgreSQL.

```sql
#=> CREATE TABLE t("C" TEXT);
CREATE TABLE
#=> SELECT c FROM t;
ERROR:  column "c" does not exist
LINE 1: SELECT c FROM t;
```

**Comment by orisano** [comment]
OK, this PR does not seem to be correct, so I will make another PR.

**Pull request closed without merging**
