### PR TITLE
fix(engine/sqlite): fixed detection of column alias without AS

### LINKED ISSUE #2559: SQLite: column alias not recognized without AS
### Version

1.20.0

### What happened?

Column alias is not recognized in SQLite if AS is not specified.

```sql
-- name: Value :one
SELECT 1 x, 2 y;
```

expected:
```go
type ValueRow struct {
	X int64
	Y int64
}
```

actual:
```go
type ValueRow struct {
	Column1 int64
	Column2 int64
}
```

It works well with the following.
```sql
-- name: Value :one
SELECT 1 AS x, 2 AS y;
```

### Relevant log output

_No response_

### Database schema

_No response_

### SQL queries

```sql
SELECT 1 x, 2 y;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "sqlite",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/7230cad224088b2a31b97ef4e18fb5dfd470a234376892879d46b5d19fd4d098

### What operating system are you using?

_No response_

### What database engines are you using?

SQLite

### What type of code are you generating?

Go

### PR DESCRIPTION
**Pull request by orisano**
fix #2559

### CODE REVIEW

**Review by kyleconroy — CHANGES_REQUESTED** [review]
For end-to-end tests, the query should be consistent across engines. In this particular case, either create a new end-to-end test or create a second named query in query.sql, adding it to the MySQL and PostgreSQL test cases as well.

**Comment by orisano** [comment]
@kyleconroy fixed!

**Comment by andrewmbenton** [comment]
I think this will need a rebase or merge from main to get tests running again.

**Comment by orisano** [comment]
@andrewmbenton rebased!

**Comment by andrewmbenton** [comment]
Looks good to me. @kyleconroy do these tests look alright?

**Review by kyleconroy — APPROVED** [review]

**Pull request merged**
