### PR TITLE
feat(compiler): Support subqueries in the FROM clause

### PR DESCRIPTION
**Pull request by Jille**
issue #2989, #2400 and probably others

### CODE REVIEW

**Comment by Jille** [comment]
I've based this on https://github.com/sqlc-dev/sqlc/pull/3220, so let's merge that first.

@SnoozeThis https://github.com/sqlc-dev/sqlc/pull/3220

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/tnvQn2qtHWc) I will wait until https://github.com/sqlc-dev/sqlc/pull/3220 is merged and then add a comment.

**Comment by kyleconroy** [comment]
I had to revert this PR as it was causing quite a few tests to fail.

**Comment by simonklee** [comment]
> I had to revert this PR as it was causing quite a few tests to fail.

I don't quite understand the CI setup if the checks passed in the PR but failed after merge.

Could you, if possible, re-run checks in https://github.com/sqlc-dev/sqlc/pull/3220 and this PR separately to identify where the regression is. As I [wrote](https://github.com/sqlc-dev/sqlc/issues/3219#issuecomment-2016706291) in the issue related to #3220. I haven't had issues with the changeset to that PR.

**Comment by msbatarce** [comment]
I was waiting for this PR, just downloaded version 1.26, mainly for #3219, but when it didn't worked I got here. Hope this can be solved, thanks to everyone for making sqlc great.

**Comment by kyleconroy** [comment]
This branch needs to be rebased on main. Once that happens, the failing tests will show up.

**Comment by Jille** [comment]
https://github.com/sqlc-dev/sqlc/actions/runs/8534508908/job/23379055224?pr=3310

The failing tests are because @simonklee's PR was open for so long, there was a version bump in between (from 1.25 -> 1.26) which caused the tests to fail :(

**Comment by SnoozeThis** [comment]
An error occurred while snoozing: not found

**Pull request merged**
