### PR TITLE
docs: add sqlc-gen-from-template

### PR DESCRIPTION
**Pull request by fdietze**
I hope this helps with adoption.

### CODE REVIEW

**Comment by kyleconroy** [comment]
Could you please add this to the new list of community projects? I think that's a better place for it.

**Comment by fdietze** [comment]
Sure. You mean the table above? Or is there a newer list?

**Comment by fdietze** [comment]
I put `Stable` in the database support section, because stability depends on your own template.

**Comment by ghandic** [comment]
Is there a place we can add a link to language templates using this? How should it be structured?

**Pull request merged**
